package com.std.persist.model;

import java.io.Serializable;
import java.util.Date;

public class SysManagerGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-manager-group.n_id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-manager-group.n_manager_id
     *
     * @mbggenerated
     */
    private Long managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-manager-group.n_group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-manager-group.s_show
     *
     * @mbggenerated
     */
    private String show;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-manager-group.s_master
     *
     * @mbggenerated
     */
    private String master;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-manager-group.d_create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-manager-group.n_state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-manager-group.n_id
     *
     * @return the value of sys-manager-group.n_id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-manager-group.n_id
     *
     * @param id the value for sys-manager-group.n_id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-manager-group.n_manager_id
     *
     * @return the value of sys-manager-group.n_manager_id
     *
     * @mbggenerated
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-manager-group.n_manager_id
     *
     * @param managerId the value for sys-manager-group.n_manager_id
     *
     * @mbggenerated
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-manager-group.n_group_id
     *
     * @return the value of sys-manager-group.n_group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-manager-group.n_group_id
     *
     * @param groupId the value for sys-manager-group.n_group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-manager-group.s_show
     *
     * @return the value of sys-manager-group.s_show
     *
     * @mbggenerated
     */
    public String getShow() {
        return show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-manager-group.s_show
     *
     * @param show the value for sys-manager-group.s_show
     *
     * @mbggenerated
     */
    public void setShow(String show) {
        this.show = show == null ? null : show.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-manager-group.s_master
     *
     * @return the value of sys-manager-group.s_master
     *
     * @mbggenerated
     */
    public String getMaster() {
        return master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-manager-group.s_master
     *
     * @param master the value for sys-manager-group.s_master
     *
     * @mbggenerated
     */
    public void setMaster(String master) {
        this.master = master == null ? null : master.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-manager-group.d_create_date
     *
     * @return the value of sys-manager-group.d_create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-manager-group.d_create_date
     *
     * @param createDate the value for sys-manager-group.d_create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-manager-group.n_state
     *
     * @return the value of sys-manager-group.n_state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-manager-group.n_state
     *
     * @param state the value for sys-manager-group.n_state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}