package com.std.persist.model;

import java.io.Serializable;
import java.util.Date;

public class SysPermission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.n_id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.n_parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.s_name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.s_tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.s_url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.s_permissions
     *
     * @mbggenerated
     */
    private String permissions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.s_class_icon
     *
     * @mbggenerated
     */
    private String classIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.n_order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.n_type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.d_create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.d_update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys-permission.n_state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys-permission
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.n_id
     *
     * @return the value of sys-permission.n_id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.n_id
     *
     * @param id the value for sys-permission.n_id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.n_parent_id
     *
     * @return the value of sys-permission.n_parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.n_parent_id
     *
     * @param parentId the value for sys-permission.n_parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.s_name
     *
     * @return the value of sys-permission.s_name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.s_name
     *
     * @param name the value for sys-permission.s_name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.s_tag
     *
     * @return the value of sys-permission.s_tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.s_tag
     *
     * @param tag the value for sys-permission.s_tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.s_url
     *
     * @return the value of sys-permission.s_url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.s_url
     *
     * @param url the value for sys-permission.s_url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.s_permissions
     *
     * @return the value of sys-permission.s_permissions
     *
     * @mbggenerated
     */
    public String getPermissions() {
        return permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.s_permissions
     *
     * @param permissions the value for sys-permission.s_permissions
     *
     * @mbggenerated
     */
    public void setPermissions(String permissions) {
        this.permissions = permissions == null ? null : permissions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.s_class_icon
     *
     * @return the value of sys-permission.s_class_icon
     *
     * @mbggenerated
     */
    public String getClassIcon() {
        return classIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.s_class_icon
     *
     * @param classIcon the value for sys-permission.s_class_icon
     *
     * @mbggenerated
     */
    public void setClassIcon(String classIcon) {
        this.classIcon = classIcon == null ? null : classIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.n_order_num
     *
     * @return the value of sys-permission.n_order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.n_order_num
     *
     * @param orderNum the value for sys-permission.n_order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.n_type
     *
     * @return the value of sys-permission.n_type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.n_type
     *
     * @param type the value for sys-permission.n_type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.d_create_date
     *
     * @return the value of sys-permission.d_create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.d_create_date
     *
     * @param createDate the value for sys-permission.d_create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.d_update_date
     *
     * @return the value of sys-permission.d_update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.d_update_date
     *
     * @param updateDate the value for sys-permission.d_update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys-permission.n_state
     *
     * @return the value of sys-permission.n_state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys-permission.n_state
     *
     * @param state the value for sys-permission.n_state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}