package com.std.persist.mysql.dao;

import com.std.persist.model.SysManagerRole;
import com.std.persist.model.SysManagerRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysManagerRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    int countByExample(SysManagerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    int deleteByExample(SysManagerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    int insert(SysManagerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    int insertSelective(SysManagerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    List<SysManagerRole> selectByExample(SysManagerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    SysManagerRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysManagerRole record, @Param("example") SysManagerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysManagerRole record, @Param("example") SysManagerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysManagerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysManagerRole record);
}