package com.std.persist.mysql.dao;

import com.std.persist.model.SysManager;
import com.std.persist.model.SysManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysManagerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    int countByExample(SysManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    int deleteByExample(SysManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    int insert(SysManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    int insertSelective(SysManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    List<SysManager> selectByExample(SysManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    SysManager selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysManager record, @Param("example") SysManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysManager record, @Param("example") SysManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysManager record);
}