package com.std.persist.mysql.dao;

import com.std.persist.model.SysGroup;
import com.std.persist.model.SysGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    int countByExample(SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    int deleteByExample(SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    int insert(SysGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    int insertSelective(SysGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    List<SysGroup> selectByExample(SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    SysGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysGroup record, @Param("example") SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysGroup record, @Param("example") SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysGroup record);
}