package com.std.persist.mysql.dao;

import com.std.persist.model.SysManagerGroup;
import com.std.persist.model.SysManagerGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysManagerGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    int countByExample(SysManagerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    int deleteByExample(SysManagerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    int insert(SysManagerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    int insertSelective(SysManagerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    List<SysManagerGroup> selectByExample(SysManagerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    SysManagerGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysManagerGroup record, @Param("example") SysManagerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysManagerGroup record, @Param("example") SysManagerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysManagerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-manager-group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysManagerGroup record);
}