package com.std.persist.mysql.dao;

import com.std.persist.model.SysRolePermission;
import com.std.persist.model.SysRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysRolePermissionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    int countByExample(SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    int deleteByExample(SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    int insert(SysRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    int insertSelective(SysRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    List<SysRolePermission> selectByExample(SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    SysRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRolePermission record, @Param("example") SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRolePermission record, @Param("example") SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys-role-permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRolePermission record);
}